### ISSUE TITLE
Problem with importing from sql file

### ISSUE THREAD

**Issue by jrperezr** [Radom12/DBMS-Apartment-Management-System-Project#1]
The error appears when importing the file
/* SQL error (1215): Cannot add foreign key constraint */

![imagen](https://github.com/Radom12/DBMS-Apartment-Management-System-Project/assets/166665298/9ff916c1-13e5-43ed-bc31-3da18108f723)

Could you please review it?
Best regards,
Richard.

**Comment by Radom12** [comment]
Have Committed the Updated SQL file.
